/**
 * Bundled facts library (Decision 3): a local static asset so a completion
 * can reward with NO network (offline-safe). Content-versioned INDEPENDENTLY
 * of schema — adding facts bumps CONTENT_VERSION only, never a migration.
 *
 * Fact IDs are STABLE and NEVER REUSED: `fact_unlocks` references them, so a
 * removed fact's id must stay retired forever (P4 — a fact is never un-seen).
 *
 * Accuracy is a hard requirement (PRD §4.5): every fact here is a
 * well-established, verifiable statement. When in doubt, it was left out.
 */

export type FactCategory = 'biology' | 'history' | 'mma' | 'strategy' | 'mythology'

export interface Fact {
  /** Stable, never reused. */
  id: string
  category: FactCategory
  text: string
}

/** Bump when facts are added/edited; unrelated to schema_version. */
export const CONTENT_VERSION = 2

/** Display names for the five categories (used by the reveal card + collection). */
export const CATEGORY_LABEL: Record<FactCategory, string> = {
  biology: 'Biology',
  history: 'History',
  mma: 'MMA',
  strategy: 'Strategy',
  mythology: 'Mythology',
}

export const FACTS: readonly Fact[] = [
  // ── Biology ──────────────────────────────────────────────────────────────
  { id: 'bio-001', category: 'biology', text: 'Octopuses have three hearts: two pump blood through the gills, and one pumps it through the rest of the body.' },
  { id: 'bio-002', category: 'biology', text: 'Human red blood cells have no nucleus, which leaves more room to carry oxygen.' },
  { id: 'bio-003', category: 'biology', text: 'The DNA in a single human cell would stretch about two metres if unravelled.' },
  { id: 'bio-004', category: 'biology', text: 'Tardigrades can survive being dried out, frozen near absolute zero, and even the vacuum of space.' },
  { id: 'bio-005', category: 'biology', text: 'Bees communicate the direction and distance of food through a "waggle dance".' },
  { id: 'bio-006', category: 'biology', text: 'Your body contains roughly as many bacterial cells as human cells.' },
  { id: 'bio-007', category: 'biology', text: 'Sharks existed before trees: sharks date back over 400 million years, trees around 385 million.' },
  { id: 'bio-008', category: 'biology', text: 'The axolotl can regenerate entire limbs, parts of its heart, and even portions of its brain.' },
  { id: 'bio-009', category: 'biology', text: 'Mammalian lungs never fully empty — a residual volume of air always remains.' },
  { id: 'bio-010', category: 'biology', text: 'Bird bones are often hollow with internal struts, keeping them light but strong for flight.' },
  { id: 'bio-011', category: 'biology', text: 'The giant sequoia is the largest tree by volume, growing to over 80 metres tall.' },
  { id: 'bio-012', category: 'biology', text: 'Photosynthesis releases the oxygen we breathe, split from water molecules, not from carbon dioxide.' },
  { id: 'bio-013', category: 'biology', text: 'A human sneeze can travel out of the nose and mouth at over 100 kilometres per hour.' },
  { id: 'bio-014', category: 'biology', text: 'Honey never spoils; sealed jars found in ancient Egyptian tombs were still edible.' },
  { id: 'bio-015', category: 'biology', text: 'Nerve impulses in humans can travel at over 100 metres per second.' },
  { id: 'bio-016', category: 'biology', text: 'The blue whale is the largest animal known to have ever lived, bigger than any dinosaur.' },
  { id: 'bio-017', category: 'biology', text: 'The human brain uses roughly 20 percent of the body’s energy despite being about 2 percent of its weight.' },
  { id: 'bio-018', category: 'biology', text: 'Tooth enamel is the hardest substance the human body produces.' },
  { id: 'bio-019', category: 'biology', text: 'Sea stars have no brain and no blood; they move seawater through their bodies instead.' },
  { id: 'bio-020', category: 'biology', text: 'Some snails can seal themselves away and survive long dry spells in a dormant state called estivation.' },
  { id: 'bio-021', category: 'biology', text: 'Chameleons change colour largely to regulate temperature and signal mood, not only to camouflage.' },
  { id: 'bio-022', category: 'biology', text: 'The heart of a shrew can beat hundreds of times per minute.' },
  { id: 'bio-023', category: 'biology', text: 'Cows have a stomach with four compartments to help them digest tough plant material.' },
  { id: 'bio-024', category: 'biology', text: 'The platypus is one of the few mammals that lays eggs rather than giving birth to live young.' },
  { id: 'bio-025', category: 'biology', text: 'Jellyfish have drifted the oceans for hundreds of millions of years, long before the dinosaurs.' },
  { id: 'bio-026', category: 'biology', text: 'Ants can carry many times their own body weight.' },
  { id: 'bio-027', category: 'biology', text: 'The human eye can distinguish millions of different colours.' },
  { id: 'bio-028', category: 'biology', text: 'Many trees share water and nutrients through underground networks of fungi.' },
  { id: 'bio-029', category: 'biology', text: 'A hummingbird can beat its wings dozens of times per second and hover in place.' },
  { id: 'bio-030', category: 'biology', text: 'One of the largest known organisms is a honey fungus in Oregon spanning several square kilometres.' },
  { id: 'bio-031', category: 'biology', text: 'Bird bones are often hollow with internal struts, keeping them light yet strong for flight.' },
  { id: 'bio-032', category: 'biology', text: 'The blue whale’s heart is roughly the size of a small car.' },
  { id: 'bio-033', category: 'biology', text: 'Octopuses and squid have blue blood because it carries oxygen using copper rather than iron.' },
  { id: 'bio-034', category: 'biology', text: 'Frogs can absorb water and partly breathe through their skin.' },
  { id: 'bio-035', category: 'biology', text: 'A newborn kangaroo is about the size of a jellybean.' },
  { id: 'bio-036', category: 'biology', text: 'Most of the human genome does not directly code for proteins.' },
  { id: 'bio-037', category: 'biology', text: 'Bamboo is among the fastest-growing plants, able to grow dramatically in a single day.' },
  { id: 'bio-038', category: 'biology', text: 'Elephants are among the few animals that can recognise themselves in a mirror.' },
  { id: 'bio-039', category: 'biology', text: 'Many deep-sea creatures make their own light through a chemical reaction called bioluminescence.' },
  { id: 'bio-040', category: 'biology', text: 'The stomach’s lining renews itself every few days so it does not digest itself.' },
  { id: 'bio-041', category: 'biology', text: 'Wombats produce cube-shaped droppings.' },
  { id: 'bio-042', category: 'biology', text: 'Flamingos get their pink colour from pigments in the algae and shrimp they eat.' },
  { id: 'bio-043', category: 'biology', text: 'Sloths move so slowly that algae can grow in their fur.' },
  { id: 'bio-044', category: 'biology', text: 'The immune system can "remember" past infections, which is how vaccines work.' },
  { id: 'bio-045', category: 'biology', text: 'Crocodiles have one of the strongest bite forces of any living animal.' },
  { id: 'bio-046', category: 'biology', text: 'Whales are mammals that evolved from four-legged land-dwelling ancestors.' },
  { id: 'bio-047', category: 'biology', text: 'The peregrine falcon is the fastest animal, exceeding 300 km/h in a hunting dive.' },
  { id: 'bio-048', category: 'biology', text: 'A single teaspoon of healthy soil can contain billions of microorganisms.' },
  { id: 'bio-049', category: 'biology', text: 'Human fingernails grow faster than toenails.' },
  { id: 'bio-050', category: 'biology', text: 'Bats are the only mammals capable of true sustained flight.' },
  { id: 'bio-051', category: 'biology', text: 'Coral reefs cover a tiny fraction of the ocean yet support a large share of marine species.' },
  { id: 'bio-052', category: 'biology', text: 'The giant panda eats mostly bamboo despite having the digestive system of a carnivore.' },
  { id: 'bio-053', category: 'biology', text: 'One species of jellyfish can revert to an earlier life stage under stress, cheating death.' },
  { id: 'bio-054', category: 'biology', text: 'Owls cannot move their eyes in their sockets, so they turn their heads to look around.' },
  { id: 'bio-055', category: 'biology', text: 'Mosquitoes are among the deadliest animals to humans because of the diseases they spread.' },
  { id: 'bio-056', category: 'biology', text: 'A cheetah can out-accelerate most sports cars over a short distance.' },
  { id: 'bio-057', category: 'biology', text: 'In seahorses, it is the male that carries and gives birth to the young.' },
  { id: 'bio-058', category: 'biology', text: 'A Venus flytrap snaps shut only after its trigger hairs are touched in quick succession.' },
  { id: 'bio-059', category: 'biology', text: 'Dolphins sleep with one half of the brain at a time so they can keep surfacing to breathe.' },
  { id: 'bio-060', category: 'biology', text: 'A woodpecker’s skull has adaptations that cushion its brain from repeated impacts.' },
  { id: 'bio-061', category: 'biology', text: 'The naked mole-rat is remarkably resistant to cancer and can survive with very little oxygen.' },
  { id: 'bio-062', category: 'biology', text: 'Butterflies taste with sensors on their feet.' },
  { id: 'bio-063', category: 'biology', text: 'The Rafflesia produces one of the largest flowers, up to about a metre across, smelling of rotting meat.' },
  { id: 'bio-064', category: 'biology', text: 'Humans share a majority of their genes with fruit flies.' },
  { id: 'bio-065', category: 'biology', text: 'A cockroach can survive for a while without its head before dying, largely of thirst.' },
  { id: 'bio-066', category: 'biology', text: 'The African elephant is the largest living land animal.' },
  { id: 'bio-067', category: 'biology', text: 'Some bacteria thrive in extreme places such as hot springs and deep-sea vents.' },
  { id: 'bio-068', category: 'biology', text: 'A snail’s slime lets it crawl over a sharp edge without being cut.' },
  { id: 'bio-069', category: 'biology', text: 'The human liver can regenerate lost tissue and regrow toward its original size.' },
  { id: 'bio-070', category: 'biology', text: 'Penguins are flightless birds but powerful swimmers.' },
  { id: 'bio-071', category: 'biology', text: 'The electric eel can generate a strong electric shock to stun prey and deter predators.' },
  { id: 'bio-072', category: 'biology', text: 'A giraffe’s neck has the same number of vertebrae as a human’s — seven.' },
  { id: 'bio-073', category: 'biology', text: 'Coast redwoods are among the tallest living things, exceeding 100 metres in height.' },
  { id: 'bio-074', category: 'biology', text: 'The human nose can detect a very large range of distinct scents.' },
  { id: 'bio-075', category: 'biology', text: 'Corals are animals that build reefs by laying down calcium carbonate skeletons.' },
  { id: 'bio-076', category: 'biology', text: 'An adult human body is made up of tens of trillions of cells.' },
  { id: 'bio-077', category: 'biology', text: 'The mantis shrimp has one of the most complex visual systems in the animal kingdom.' },
  { id: 'bio-078', category: 'biology', text: 'Salmon can navigate back to the very stream where they hatched in order to spawn.' },
  { id: 'bio-079', category: 'biology', text: 'A ladybird can eat thousands of aphids over its lifetime.' },
  { id: 'bio-080', category: 'biology', text: 'A resting blue whale’s heart can slow to just a few beats per minute.' },
  { id: 'bio-081', category: 'biology', text: 'Trees add a growth ring each year, recording their age and the climate they grew in.' },
  { id: 'bio-082', category: 'biology', text: 'Some frogs can freeze partly solid in winter and thaw back to life in spring.' },
  { id: 'bio-083', category: 'biology', text: 'Bees must visit a great many flowers to make a single jar of honey.' },
  { id: 'bio-084', category: 'biology', text: 'The largest land carnivore is the polar bear.' },
  { id: 'bio-085', category: 'biology', text: 'Ferns reproduce using spores rather than seeds or flowers.' },
  { id: 'bio-086', category: 'biology', text: 'A hagfish can produce large amounts of slime to defend itself from predators.' },
  { id: 'bio-087', category: 'biology', text: 'Many migratory birds can sense the Earth’s magnetic field to help them navigate.' },
  { id: 'bio-088', category: 'biology', text: 'Much of the oxygen produced on Earth comes from ocean phytoplankton, not only from forests.' },
  { id: 'bio-089', category: 'biology', text: 'An octopus can squeeze its soft body through any gap larger than its beak.' },
  { id: 'bio-090', category: 'biology', text: 'The star-nosed mole uses a ring of fleshy tentacles to feel its way and find food quickly.' },
  { id: 'bio-091', category: 'biology', text: 'A tree frog’s toe pads let it cling to smooth surfaces like leaves and glass.' },
  { id: 'bio-092', category: 'biology', text: 'Reindeer eyes can shift colour between summer and winter to adjust to the changing light.' },
  { id: 'bio-093', category: 'biology', text: 'Some cicadas spend more than a decade underground before emerging to breed.' },
  { id: 'bio-094', category: 'biology', text: 'The blue whale’s call is among the loudest sounds made by any animal.' },
  { id: 'bio-095', category: 'biology', text: 'Human taste relies heavily on smell, which is why food seems bland with a blocked nose.' },
  { id: 'bio-096', category: 'biology', text: 'The axolotl keeps its larval features, including external gills, throughout adult life.' },
  { id: 'bio-097', category: 'biology', text: 'Emperor penguin fathers incubate their egg on their feet through the Antarctic winter.' },
  { id: 'bio-098', category: 'biology', text: 'Kangaroos struggle to move backwards because of their large tail and feet.' },
  { id: 'bio-099', category: 'biology', text: 'Geckos can climb smooth walls thanks to microscopic hairs on their toes.' },
  { id: 'bio-100', category: 'biology', text: 'The human body constantly replaces old cells, so most of it is renewed over time.' },

  // ── History ──────────────────────────────────────────────────────────────
  { id: 'his-001', category: 'history', text: 'The Great Pyramid of Giza was the tallest human-made structure on Earth for over 3,800 years.' },
  { id: 'his-002', category: 'history', text: 'Oxford University was teaching students before the Aztec Empire founded its capital, Tenochtitlan.' },
  { id: 'his-003', category: 'history', text: 'Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.' },
  { id: 'his-004', category: 'history', text: 'The printing press with movable type was introduced to Europe by Johannes Gutenberg around 1440.' },
  { id: 'his-005', category: 'history', text: 'The Roman concrete used in structures like the Pantheon can be more durable than many modern concretes.' },
  { id: 'his-006', category: 'history', text: 'The Rosetta Stone, found in 1799, was the key to deciphering Egyptian hieroglyphs.' },
  { id: 'his-007', category: 'history', text: 'The Library of Alexandria was one of the largest centres of learning in the ancient world.' },
  { id: 'his-008', category: 'history', text: 'The Black Death in the 14th century killed an estimated one-third of Europe’s population.' },
  { id: 'his-009', category: 'history', text: 'The first successful powered aeroplane flight by the Wright brothers, in 1903, lasted about 12 seconds.' },
  { id: 'his-010', category: 'history', text: 'The Berlin Wall stood from 1961 until it was opened in 1989, dividing the city for 28 years.' },
  { id: 'his-011', category: 'history', text: 'Genghis Khan’s Mongol Empire became the largest contiguous land empire in history.' },
  { id: 'his-012', category: 'history', text: 'The Magna Carta, sealed in 1215, limited the English king’s power and influenced later constitutions.' },
  { id: 'his-013', category: 'history', text: 'Ancient Rome had a population of roughly one million people at its height.' },
  { id: 'his-014', category: 'history', text: 'The Great Fire of London in 1666 destroyed much of the medieval city within the old Roman walls.' },
  { id: 'his-015', category: 'history', text: 'Vikings reached North America around the year 1000, roughly 500 years before Columbus.' },
  { id: 'his-016', category: 'history', text: 'The Colosseum in Rome could hold tens of thousands of spectators for its games.' },
  { id: 'his-017', category: 'history', text: 'The Silk Road was a network of trade routes linking Asia, the Middle East, and Europe.' },
  { id: 'his-018', category: 'history', text: 'Ancient Egyptians wrote on a paper-like material made from the papyrus plant.' },
  { id: 'his-019', category: 'history', text: 'The wheel first appeared thousands of years ago, used for pottery before transport.' },
  { id: 'his-020', category: 'history', text: 'At its height the Roman Empire controlled lands all around the Mediterranean Sea.' },
  { id: 'his-021', category: 'history', text: 'The Renaissance, beginning in Italy, revived interest in classical art, science, and learning.' },
  { id: 'his-022', category: 'history', text: 'The Hundred Years’ War between England and France actually lasted more than a hundred years.' },
  { id: 'his-023', category: 'history', text: 'The Great Wall of China was built and rebuilt over many centuries by different dynasties.' },
  { id: 'his-024', category: 'history', text: 'The first modern Olympic Games were held in Athens in 1896.' },
  { id: 'his-025', category: 'history', text: 'Gunpowder was invented in China and later spread westward.' },
  { id: 'his-026', category: 'history', text: 'The French Revolution began in 1789 and reshaped ideas of citizenship and government.' },
  { id: 'his-027', category: 'history', text: 'The Industrial Revolution began in Britain in the 18th century, transforming manufacturing.' },
  { id: 'his-028', category: 'history', text: 'The city of Pompeii was buried by the eruption of Mount Vesuvius in AD 79.' },
  { id: 'his-029', category: 'history', text: 'Julius Caesar was assassinated in Rome in 44 BC.' },
  { id: 'his-030', category: 'history', text: 'The magnetic compass, developed in China, transformed navigation and exploration.' },
  { id: 'his-031', category: 'history', text: 'The United States Declaration of Independence was adopted in 1776.' },
  { id: 'his-032', category: 'history', text: 'Ancient Athens is often called the birthplace of democracy.' },
  { id: 'his-033', category: 'history', text: 'The Ottomans captured Constantinople in 1453, ending the Byzantine Empire.' },
  { id: 'his-034', category: 'history', text: 'The first steam-powered passenger railways opened in the early 19th century.' },
  { id: 'his-035', category: 'history', text: 'The Aztec capital Tenochtitlan stood on an island where Mexico City is today.' },
  { id: 'his-036', category: 'history', text: 'Mesopotamia, between the Tigris and Euphrates, is often called the cradle of civilisation.' },
  { id: 'his-037', category: 'history', text: 'The Code of Hammurabi is one of the oldest known written sets of laws.' },
  { id: 'his-038', category: 'history', text: 'The Inca built an extensive Andean road network without the wheel or iron tools.' },
  { id: 'his-039', category: 'history', text: 'The telegraph let messages travel over long distances almost instantly in the 19th century.' },
  { id: 'his-040', category: 'history', text: 'The Spanish Armada, sent to invade England, was defeated in 1588.' },
  { id: 'his-041', category: 'history', text: 'Edward Jenner developed the first successful vaccine, against smallpox, in the 1790s.' },
  { id: 'his-042', category: 'history', text: 'The first transcontinental railroad across the United States was completed in 1869.' },
  { id: 'his-043', category: 'history', text: 'World War I was fought from 1914 to 1918.' },
  { id: 'his-044', category: 'history', text: 'World War II ended in 1945.' },
  { id: 'his-045', category: 'history', text: 'The Wright brothers made their first powered flights at Kitty Hawk, North Carolina.' },
  { id: 'his-046', category: 'history', text: 'Ancient Sparta was known for its rigorous military training and disciplined society.' },
  { id: 'his-047', category: 'history', text: 'The Byzantine Empire was the eastern continuation of Rome, centred on Constantinople.' },
  { id: 'his-048', category: 'history', text: 'The Statue of Liberty was a gift from France to the United States, dedicated in 1886.' },
  { id: 'his-049', category: 'history', text: 'Marco Polo’s 13th-century travels brought Europe vivid accounts of Asia.' },
  { id: 'his-050', category: 'history', text: 'The ancient Olympic Games were held at Olympia in Greece for many centuries.' },
  { id: 'his-051', category: 'history', text: 'Leonardo da Vinci was a painter, inventor, and scientist of the Italian Renaissance.' },
  { id: 'his-052', category: 'history', text: 'The Cold War was a decades-long rivalry between the United States and the Soviet Union.' },
  { id: 'his-053', category: 'history', text: 'The Apollo 11 mission landed the first humans on the Moon in 1969.' },
  { id: 'his-054', category: 'history', text: 'The Titanic sank in 1912 after striking an iceberg on its maiden voyage.' },
  { id: 'his-055', category: 'history', text: 'Slavery was abolished across most of the British Empire in the 1830s.' },
  { id: 'his-056', category: 'history', text: 'The Reformation, begun by Martin Luther in 1517, split Western Christianity.' },
  { id: 'his-057', category: 'history', text: 'The Han dynasty was one of the longest and most influential in Chinese history.' },
  { id: 'his-058', category: 'history', text: 'The Nile’s annual flooding made ancient Egyptian agriculture possible.' },
  { id: 'his-059', category: 'history', text: 'By legend, the city of Rome was founded in 753 BC.' },
  { id: 'his-060', category: 'history', text: 'The printing press greatly accelerated the spread of books and ideas across Europe.' },
  { id: 'his-061', category: 'history', text: 'The Crusades were a series of religious wars during the medieval period.' },
  { id: 'his-062', category: 'history', text: 'Michelangelo painted the ceiling of the Sistine Chapel during the Renaissance.' },
  { id: 'his-063', category: 'history', text: 'James Watt’s improvements to the steam engine helped power the Industrial Revolution.' },
  { id: 'his-064', category: 'history', text: 'The ancient Maya developed a sophisticated calendar and a system of writing.' },
  { id: 'his-065', category: 'history', text: 'Alexander Graham Bell was granted a patent for the telephone in 1876.' },
  { id: 'his-066', category: 'history', text: 'Napoleon rose to power after the French Revolution and crowned himself emperor.' },
  { id: 'his-067', category: 'history', text: 'The Berlin Wall fell in 1989, marking the end of the Cold War in Europe.' },
  { id: 'his-068', category: 'history', text: 'The Panama Canal, opened in 1914, joined the Atlantic and Pacific Oceans.' },
  { id: 'his-069', category: 'history', text: 'The ancient Persians built the Royal Road to speed communication across their empire.' },
  { id: 'his-070', category: 'history', text: 'Joan of Arc led French forces during the Hundred Years’ War before her death in 1431.' },
  { id: 'his-071', category: 'history', text: 'The Rosetta Stone carries the same decree in three scripts, which unlocked hieroglyphs.' },
  { id: 'his-072', category: 'history', text: 'The Gutenberg Bible was among the first major books printed with movable type in Europe.' },
  { id: 'his-073', category: 'history', text: 'The American Civil War was fought between 1861 and 1865.' },
  { id: 'his-074', category: 'history', text: 'The Suez Canal, opened in 1869, linked the Mediterranean and Red Seas.' },
  { id: 'his-075', category: 'history', text: 'Christopher Columbus reached the Americas in 1492 while seeking a westward route to Asia.' },
  { id: 'his-076', category: 'history', text: 'The Renaissance spread from Italy across much of Europe over the 15th and 16th centuries.' },
  { id: 'his-077', category: 'history', text: 'The ancient Egyptians mummified the dead to preserve them for the afterlife.' },
  { id: 'his-078', category: 'history', text: 'The Roman road network was so extensive that many modern roads still follow its routes.' },
  { id: 'his-079', category: 'history', text: 'The Magna Carta influenced the later development of constitutional government.' },
  { id: 'his-080', category: 'history', text: 'The first powered aeroplane flight lasted only seconds but changed transport forever.' },
  { id: 'his-081', category: 'history', text: 'Athens built the Parthenon on the Acropolis in the 5th century BC.' },
  { id: 'his-082', category: 'history', text: 'The abacus was one of the earliest tools for calculation.' },
  { id: 'his-083', category: 'history', text: 'The Vikings were skilled seafarers who raided, traded, and settled across Europe.' },
  { id: 'his-084', category: 'history', text: 'The Great Depression began after the stock market crash of 1929.' },
  { id: 'his-085', category: 'history', text: 'Europe’s first universities were founded during the medieval period.' },
  { id: 'his-086', category: 'history', text: 'Ancient Egyptians tracked the year using the rising of the star Sirius and the Nile’s flood.' },
  { id: 'his-087', category: 'history', text: 'The Renaissance saw the rediscovery of many ancient Greek and Roman texts.' },
  { id: 'his-088', category: 'history', text: 'Printed newspapers helped spread news widely by the 17th century.' },
  { id: 'his-089', category: 'history', text: 'The Roman numeral system used letters to represent numbers.' },
  { id: 'his-090', category: 'history', text: 'Better ships and navigation enabled the European Age of Exploration.' },
  { id: 'his-091', category: 'history', text: 'The Library of Alexandria sought to gather the knowledge of the known world.' },
  { id: 'his-092', category: 'history', text: 'The Taj Mahal in India was built in the 17th century as a mausoleum.' },
  { id: 'his-093', category: 'history', text: 'The Boston Tea Party of 1773 was a protest against British taxation.' },
  { id: 'his-094', category: 'history', text: 'Renaissance banking families such as the Medici funded much art and learning.' },
  { id: 'his-095', category: 'history', text: 'The ancient Greeks staged festivals of tragedy and comedy in open-air theatres.' },
  { id: 'his-096', category: 'history', text: 'The steam locomotive dramatically cut travel times in the 19th century.' },
  { id: 'his-097', category: 'history', text: 'The pyramids of Giza were built as tombs for Egyptian pharaohs.' },
  { id: 'his-098', category: 'history', text: 'Galileo improved the telescope and championed a Sun-centred model of the heavens.' },
  { id: 'his-099', category: 'history', text: 'The fall of the Western Roman Empire is traditionally dated to AD 476.' },
  { id: 'his-100', category: 'history', text: 'The Declaration of the Rights of Man was a key document of the French Revolution.' },

  // ── MMA / combat sports ──────────────────────────────────────────────────
  { id: 'mma-001', category: 'mma', text: 'The UFC held its first event, UFC 1, in Denver, Colorado, in November 1993.' },
  { id: 'mma-002', category: 'mma', text: 'Royce Gracie won the first UFC tournament, showcasing Brazilian Jiu-Jitsu against larger opponents.' },
  { id: 'mma-003', category: 'mma', text: 'The term "mixed martial arts" describes combining striking and grappling from different disciplines.' },
  { id: 'mma-004', category: 'mma', text: 'A "triangle choke" uses the legs to encircle an opponent’s neck and one arm.' },
  { id: 'mma-005', category: 'mma', text: 'Amanda Nunes is the first woman to hold UFC titles in two weight classes simultaneously.' },
  { id: 'mma-006', category: 'mma', text: 'The "octagon", the UFC’s eight-sided cage, has become a signature of the sport.' },
  { id: 'mma-007', category: 'mma', text: 'Muay Thai is known as "the art of eight limbs" because it uses fists, elbows, knees, and shins.' },
  { id: 'mma-008', category: 'mma', text: 'Brazilian Jiu-Jitsu was developed by the Gracie family from Japanese judo and jujutsu.' },
  { id: 'mma-009', category: 'mma', text: 'The Unified Rules of MMA introduced weight classes and rounds to standardise the sport.' },
  { id: 'mma-010', category: 'mma', text: 'A "rear-naked choke" is a blood choke applied from behind, restricting blood flow rather than air.' },
  { id: 'mma-011', category: 'mma', text: 'Anderson Silva holds one of the longest title-defence streaks in UFC middleweight history.' },
  { id: 'mma-012', category: 'mma', text: 'Georges St-Pierre is celebrated for blending wrestling, striking, and jiu-jitsu into a complete game.' },
  { id: 'mma-013', category: 'mma', text: 'Judo, a foundation of many MMA grapplers, was founded by Jigoro Kano in Japan in 1882.' },
  { id: 'mma-014', category: 'mma', text: 'Boxing footwork and head movement are widely adopted by MMA strikers to control distance.' },
  { id: 'mma-015', category: 'mma', text: 'Wrestling’s takedown control is often decisive in MMA because it dictates where the fight happens.' },
  { id: 'mma-016', category: 'mma', text: 'The "guard" is a grappling position where a fighter on their back controls an opponent with their legs.' },
  { id: 'mma-017', category: 'mma', text: '"Ground and pound" is taking an opponent down and striking them from a top position.' },
  { id: 'mma-018', category: 'mma', text: 'A "sprawl" is a defensive move used to stop an opponent’s takedown attempt.' },
  { id: 'mma-019', category: 'mma', text: 'The "clinch" is close-range grappling while standing, used to control or strike an opponent.' },
  { id: 'mma-020', category: 'mma', text: 'An "armbar" is a joint lock that hyperextends the opponent’s elbow.' },
  { id: 'mma-021', category: 'mma', text: 'The "kimura" shoulder lock is named after the judoka Masahiko Kimura.' },
  { id: 'mma-022', category: 'mma', text: 'A "guillotine choke" attacks the front of the neck, often from the clinch or guard.' },
  { id: 'mma-023', category: 'mma', text: '"Tapping out" is the standard way a fighter signals submission to end a fight.' },
  { id: 'mma-024', category: 'mma', text: 'A knockout occurs when a fighter is rendered unable to continue, often by a strike.' },
  { id: 'mma-025', category: 'mma', text: 'A technical knockout (TKO) is called when a fighter cannot safely continue but is not knocked out.' },
  { id: 'mma-026', category: 'mma', text: 'Freestyle and Greco-Roman wrestling heavily influence MMA takedowns.' },
  { id: 'mma-027', category: 'mma', text: 'Kickboxing contributes punches and kicks to a mixed martial artist’s striking.' },
  { id: 'mma-028', category: 'mma', text: 'A "jab" is a quick, straight lead-hand punch used to measure distance and set up other strikes.' },
  { id: 'mma-029', category: 'mma', text: 'A "roundhouse kick" strikes with the shin or foot in a circular arc.' },
  { id: 'mma-030', category: 'mma', text: '"Sparring" is controlled practice fighting used in training.' },
  { id: 'mma-031', category: 'mma', text: 'The "mount" is a dominant ground position, sitting on the opponent’s torso.' },
  { id: 'mma-032', category: 'mma', text: '"Side control" is a top ground position held perpendicular to a pinned opponent.' },
  { id: 'mma-033', category: 'mma', text: 'The "half guard" is a position where one leg controls one of the opponent’s legs.' },
  { id: 'mma-034', category: 'mma', text: 'A "takedown" brings a standing opponent to the ground.' },
  { id: 'mma-035', category: 'mma', text: 'MMA gloves are lighter and more open-fingered than boxing gloves to allow grappling.' },
  { id: 'mma-036', category: 'mma', text: 'Weight classes match fighters of similar size for fairness and safety.' },
  { id: 'mma-037', category: 'mma', text: 'A UFC championship bout is scheduled for five rounds.' },
  { id: 'mma-038', category: 'mma', text: 'A standard non-title UFC bout is scheduled for three rounds.' },
  { id: 'mma-039', category: 'mma', text: 'Each round in the UFC lasts five minutes.' },
  { id: 'mma-040', category: 'mma', text: 'MMA judges commonly score rounds using a ten-point must system.' },
  { id: 'mma-041', category: 'mma', text: 'A "submission" forces an opponent to give up through a choke or joint lock.' },
  { id: 'mma-042', category: 'mma', text: 'A "leg kick" targets the opponent’s thigh to slow their movement.' },
  { id: 'mma-043', category: 'mma', text: 'Pancrase and Shooto were early Japanese organisations in the development of modern MMA.' },
  { id: 'mma-044', category: 'mma', text: 'PRIDE Fighting Championships was a major MMA promotion based in Japan.' },
  { id: 'mma-045', category: 'mma', text: 'Catch wrestling blends pins and submissions and influenced modern grappling.' },
  { id: 'mma-046', category: 'mma', text: 'Sambo is a martial art and combat sport that developed in the Soviet Union.' },
  { id: 'mma-047', category: 'mma', text: 'A "double-leg takedown" grabs both of an opponent’s legs to bring them down.' },
  { id: 'mma-048', category: 'mma', text: 'A "single-leg takedown" targets just one of the opponent’s legs.' },
  { id: 'mma-049', category: 'mma', text: 'The "north-south" position is top control aligned head-to-head with the opponent.' },
  { id: 'mma-050', category: 'mma', text: 'A "heel hook" is a leg lock that twists the ankle and knee and is considered dangerous.' },
  { id: 'mma-051', category: 'mma', text: 'The "kneebar" is a joint lock that hyperextends the knee.' },
  { id: 'mma-052', category: 'mma', text: 'An "overhand" is a looping power punch thrown over an opponent’s guard.' },
  { id: 'mma-053', category: 'mma', text: 'A "hook" is a punch thrown in a horizontal arc to the side of the head or body.' },
  { id: 'mma-054', category: 'mma', text: 'An "uppercut" is an upward punch aimed at the opponent’s chin.' },
  { id: 'mma-055', category: 'mma', text: '"Head movement" helps a striker avoid punches by slipping and rolling.' },
  { id: 'mma-056', category: 'mma', text: 'A "teep", or push kick, is used in Muay Thai to keep an opponent at distance.' },
  { id: 'mma-057', category: 'mma', text: 'The Muay Thai "plum", a double-collar clinch, controls the head to land knees.' },
  { id: 'mma-058', category: 'mma', text: 'An "omoplata" is a shoulder lock applied using the legs in Brazilian Jiu-Jitsu.' },
  { id: 'mma-059', category: 'mma', text: 'A "D’Arce choke" threads the arm under the neck for an arm-triangle-style finish.' },
  { id: 'mma-060', category: 'mma', text: 'A "bout" is another word for a single fight or match.' },
  { id: 'mma-061', category: 'mma', text: 'The referee can stop a fight to protect a fighter who can no longer defend themselves.' },
  { id: 'mma-062', category: 'mma', text: '"Cutting weight" is losing weight before a weigh-in to compete in a lower class.' },
  { id: 'mma-063', category: 'mma', text: 'A "walkout" is the entrance a fighter makes before a bout, often to music.' },
  { id: 'mma-064', category: 'mma', text: 'A "gassed" fighter is one who has become exhausted and low on stamina.' },
  { id: 'mma-065', category: 'mma', text: 'Cardiovascular conditioning is crucial to lasting through MMA rounds.' },
  { id: 'mma-066', category: 'mma', text: 'The cage or ring is the enclosed area where a bout takes place.' },
  { id: 'mma-067', category: 'mma', text: 'A "split decision" is when the judges do not unanimously agree on the winner.' },
  { id: 'mma-068', category: 'mma', text: 'A "unanimous decision" is when all judges score the fight for the same fighter.' },
  { id: 'mma-069', category: 'mma', text: 'A "majority decision" is when two judges favour a fighter and the third scores a draw.' },
  { id: 'mma-070', category: 'mma', text: 'A "draw" results when the judges’ scores do not favour either fighter overall.' },
  { id: 'mma-071', category: 'mma', text: '"Dirty boxing" is close-range punching thrown from the clinch.' },
  { id: 'mma-072', category: 'mma', text: 'The "butterfly guard" hooks the shins inside the opponent’s thighs to control and sweep.' },
  { id: 'mma-073', category: 'mma', text: 'A "sweep" reverses position so the bottom grappler ends up on top.' },
  { id: 'mma-074', category: 'mma', text: '"Passing the guard" is getting past an opponent’s legs to reach a dominant position.' },
  { id: 'mma-075', category: 'mma', text: 'A "berimbolo" is an inverted spinning technique used in modern sport Jiu-Jitsu.' },
  { id: 'mma-076', category: 'mma', text: '"Shadowboxing" is practising strikes and movement against an imaginary opponent.' },
  { id: 'mma-077', category: 'mma', text: 'A "spinning back kick" builds power by turning the body before striking.' },
  { id: 'mma-078', category: 'mma', text: 'A "front kick" strikes straight ahead with the ball of the foot or the heel.' },
  { id: 'mma-079', category: 'mma', text: 'The jab-cross combination is one of boxing’s most fundamental sequences.' },
  { id: 'mma-080', category: 'mma', text: 'A "check" blocks a leg kick by lifting the shin to absorb the impact.' },
  { id: 'mma-081', category: 'mma', text: '"Level changing" means lowering the body to set up takedowns or avoid strikes.' },
  { id: 'mma-082', category: 'mma', text: 'A "scramble" is a fast exchange as both fighters fight for position on the ground.' },
  { id: 'mma-083', category: 'mma', text: '"Posture" in the guard is a top fighter staying upright to avoid submissions.' },
  { id: 'mma-084', category: 'mma', text: 'The "rubber guard" plays the legs high on the opponent’s back to control them.' },
  { id: 'mma-085', category: 'mma', text: '"Grip fighting" is the struggle for control of the hands and wrists before a throw.' },
  { id: 'mma-086', category: 'mma', text: 'A "hip toss" uses the hip as a pivot to throw an opponent to the ground.' },
  { id: 'mma-087', category: 'mma', text: 'A "suplex" lifts and drops an opponent, a throw drawn from wrestling.' },
  { id: 'mma-088', category: 'mma', text: '"Framing" uses the arms as barriers to create space and prevent control.' },
  { id: 'mma-089', category: 'mma', text: 'A triangle choke can be finished from the guard by trapping the head and one arm with the legs.' },
  { id: 'mma-090', category: 'mma', text: 'A "flying knee" is a knee strike thrown while leaping toward the opponent.' },
  { id: 'mma-091', category: 'mma', text: '"Fight IQ" describes a fighter’s ability to make smart decisions during a bout.' },
  { id: 'mma-092', category: 'mma', text: '"Feinting" is faking a strike to provoke a reaction and create openings.' },
  { id: 'mma-093', category: 'mma', text: 'An "orthodox" stance leads with the left side; a "southpaw" stance leads with the right.' },
  { id: 'mma-094', category: 'mma', text: 'A "body lock" wraps the arms around the opponent’s torso to control or take them down.' },
  { id: 'mma-095', category: 'mma', text: '"Pummelling" is the exchange of underhooks to gain control in the clinch.' },
  { id: 'mma-096', category: 'mma', text: 'An "underhook" is an arm position beneath the opponent’s arm used for control.' },
  { id: 'mma-097', category: 'mma', text: 'An "overhook" is an arm position over the opponent’s arm.' },
  { id: 'mma-098', category: 'mma', text: 'A "guard pull" is choosing the bottom guard rather than taking an opponent down.' },
  { id: 'mma-099', category: 'mma', text: '"Ring rust" is the loss of sharpness a fighter can show after a long layoff.' },
  { id: 'mma-100', category: 'mma', text: 'Mixed martial arts blends striking, wrestling, and submission grappling into one sport.' },

  // ── Strategy ─────────────────────────────────────────────────────────────
  { id: 'str-001', category: 'strategy', text: 'Sun Tzu’s "The Art of War" argues that the greatest victory is winning without fighting.' },
  { id: 'str-002', category: 'strategy', text: 'In chess, controlling the four central squares gives pieces greater mobility and reach.' },
  { id: 'str-003', category: 'strategy', text: 'The "OODA loop" — Observe, Orient, Decide, Act — describes cycling through decisions faster than a rival.' },
  { id: 'str-004', category: 'strategy', text: 'A "Pyrrhic victory" is a win so costly it is nearly as damaging as a defeat.' },
  { id: 'str-005', category: 'strategy', text: 'In game theory, a Nash equilibrium is a state where no player gains by changing strategy alone.' },
  { id: 'str-006', category: 'strategy', text: 'The prisoner’s dilemma shows how two rational actors may fail to cooperate even when it helps both.' },
  { id: 'str-007', category: 'strategy', text: 'Hannibal’s double envelopment at Cannae is still studied as a model of encirclement.' },
  { id: 'str-008', category: 'strategy', text: 'In chess, a "gambit" sacrifices material early to gain position or initiative.' },
  { id: 'str-009', category: 'strategy', text: 'Logistics — supply, movement, and maintenance — often decides campaigns more than battles do.' },
  { id: 'str-010', category: 'strategy', text: 'The "sunk cost fallacy" is continuing something only because of what you’ve already invested.' },
  { id: 'str-011', category: 'strategy', text: 'Concentrating force at a decisive point, rather than spreading it thin, is a classic military principle.' },
  { id: 'str-012', category: 'strategy', text: 'In negotiation, knowing your best alternative to a deal (your BATNA) strengthens your position.' },
  { id: 'str-013', category: 'strategy', text: 'A "zugzwang" in chess is a position where any move a player makes worsens their situation.' },
  { id: 'str-014', category: 'strategy', text: 'Deception and surprise are recurring themes across nearly every classic treatise on strategy.' },
  { id: 'str-015', category: 'strategy', text: 'Breaking a large goal into the smallest next action lowers the effort needed to begin.' },
  { id: 'str-016', category: 'strategy', text: 'In chess, the "endgame" is the final phase when few pieces remain on the board.' },
  { id: 'str-017', category: 'strategy', text: 'Clausewitz described war as a continuation of politics by other means.' },
  { id: 'str-018', category: 'strategy', text: '"Divide and conquer" weakens an opponent by splitting their strength into smaller parts.' },
  { id: 'str-019', category: 'strategy', text: 'The "fog of war" refers to the uncertainty commanders face about the battlefield.' },
  { id: 'str-020', category: 'strategy', text: 'A "feint" is a fake attack meant to draw a response and open a gap elsewhere.' },
  { id: 'str-021', category: 'strategy', text: 'In game theory, a "zero-sum game" is one where one player’s gain is another’s loss.' },
  { id: 'str-022', category: 'strategy', text: 'The "tragedy of the commons" describes shared resources being overused out of self-interest.' },
  { id: 'str-023', category: 'strategy', text: 'A "war of attrition" seeks to win by wearing down the enemy’s resources over time.' },
  { id: 'str-024', category: 'strategy', text: 'In chess, "development" means bringing pieces into active play early.' },
  { id: 'str-025', category: 'strategy', text: '"First-mover advantage" is the benefit of acting before competitors do.' },
  { id: 'str-026', category: 'strategy', text: 'A "flanking manoeuvre" attacks an enemy from the side rather than head-on.' },
  { id: 'str-027', category: 'strategy', text: 'Guerrilla warfare uses small, mobile tactics against a larger conventional force.' },
  { id: 'str-028', category: 'strategy', text: 'The "domino theory" held that one event could trigger a chain of similar events.' },
  { id: 'str-029', category: 'strategy', text: 'In chess, "castling" improves king safety and connects the rooks in one move.' },
  { id: 'str-030', category: 'strategy', text: 'A "siege" aims to capture a fortified position by surrounding and cutting it off.' },
  { id: 'str-031', category: 'strategy', text: '"Escalation" is the increase in intensity or scope of a conflict.' },
  { id: 'str-032', category: 'strategy', text: 'A "stalemate" in chess is a draw where a player has no legal move but is not in check.' },
  { id: 'str-033', category: 'strategy', text: 'The "sunk cost fallacy" keeps people on a losing course because of past investment.' },
  { id: 'str-034', category: 'strategy', text: '"Deterrence" seeks to prevent an action by threatening unacceptable consequences.' },
  { id: 'str-035', category: 'strategy', text: 'In negotiation, "anchoring" sets an initial figure that shapes the discussion.' },
  { id: 'str-036', category: 'strategy', text: 'A "war game" is a simulation used to test strategies without real risk.' },
  { id: 'str-037', category: 'strategy', text: 'The "centre of gravity" is the source of an opponent’s strength that strategy aims to undermine.' },
  { id: 'str-038', category: 'strategy', text: 'A "gambit", broadly, is a calculated risk taken to gain an advantage.' },
  { id: 'str-039', category: 'strategy', text: '"Economy of force" spends minimal resources on secondary efforts to concentrate elsewhere.' },
  { id: 'str-040', category: 'strategy', text: 'In chess, a "fork" attacks two pieces at once with a single piece.' },
  { id: 'str-041', category: 'strategy', text: 'A "pin" in chess freezes a piece because moving it would expose a more valuable one.' },
  { id: 'str-042', category: 'strategy', text: '"Momentum" is the advantage gained from a series of successes.' },
  { id: 'str-043', category: 'strategy', text: 'A "Trojan horse" strategy hides an attack inside something that appears harmless.' },
  { id: 'str-044', category: 'strategy', text: 'Attrition versus manoeuvre is a classic contrast between wearing down and outmanoeuvring.' },
  { id: 'str-045', category: 'strategy', text: 'In chess, a "skewer" forces a valuable piece to move and exposes a lesser one behind it.' },
  { id: 'str-046', category: 'strategy', text: '"Bluffing" projects strength or intent one does not actually have.' },
  { id: 'str-047', category: 'strategy', text: 'A "pincer movement" attacks an enemy from two sides at once.' },
  { id: 'str-048', category: 'strategy', text: '"Positional play" in chess builds long-term advantages rather than seeking immediate gains.' },
  { id: 'str-049', category: 'strategy', text: 'Massing force at the decisive point is a central principle of strategy.' },
  { id: 'str-050', category: 'strategy', text: '"Reconnaissance" gathers information about an opponent before acting.' },
  { id: 'str-051', category: 'strategy', text: 'A "war chest" is a reserve of resources set aside for a campaign or contest.' },
  { id: 'str-052', category: 'strategy', text: '"Brinkmanship" pushes a dangerous situation to the edge to force an outcome.' },
  { id: 'str-053', category: 'strategy', text: 'In chess, gaining "tempo" means acting efficiently, as if a move ahead.' },
  { id: 'str-054', category: 'strategy', text: 'A "scorched earth" strategy destroys anything useful to an advancing enemy.' },
  { id: 'str-055', category: 'strategy', text: '"Asymmetric warfare" pits opponents of very different strength and methods against each other.' },
  { id: 'str-056', category: 'strategy', text: 'The prisoner’s dilemma shows how mutual cooperation can be hard even when it benefits both.' },
  { id: 'str-057', category: 'strategy', text: 'In business, a "moat" is a durable advantage that protects a company from rivals.' },
  { id: 'str-058', category: 'strategy', text: '"Opportunity cost" is the value of the best alternative given up when making a choice.' },
  { id: 'str-059', category: 'strategy', text: '"Blitzkrieg" was a fast, concentrated form of mechanised warfare.' },
  { id: 'str-060', category: 'strategy', text: 'In chess, controlling open files with rooks increases their power.' },
  { id: 'str-061', category: 'strategy', text: 'A "salient" is a battlefield position that juts into enemy-held territory.' },
  { id: 'str-062', category: 'strategy', text: '"Containment" seeks to limit the spread of an opponent’s influence.' },
  { id: 'str-063', category: 'strategy', text: 'A "beachhead" is an initial secured position from which further advances are launched.' },
  { id: 'str-064', category: 'strategy', text: '"Interior lines" let a force shift between fronts faster than an encircling enemy.' },
  { id: 'str-065', category: 'strategy', text: 'The OODA loop stresses acting faster than an opponent’s decision cycle.' },
  { id: 'str-066', category: 'strategy', text: 'A "phalanx" was a tight formation of soldiers with overlapping shields and long spears.' },
  { id: 'str-067', category: 'strategy', text: '"Suppressing fire" pins down an enemy so friendly forces can move.' },
  { id: 'str-068', category: 'strategy', text: 'A "diversion" draws attention away from the main effort.' },
  { id: 'str-069', category: 'strategy', text: '"Grand strategy" coordinates all of a nation’s resources toward long-term goals.' },
  { id: 'str-070', category: 'strategy', text: 'Tactics win individual engagements; strategy wins the overall aim.' },
  { id: 'str-071', category: 'strategy', text: 'A "chokepoint" is a narrow passage where a smaller force can hold off a larger one.' },
  { id: 'str-072', category: 'strategy', text: '"Envelopment" attacks the flank or rear of an enemy rather than the front.' },
  { id: 'str-073', category: 'strategy', text: 'The "high ground" offers advantages of visibility and momentum in a fight.' },
  { id: 'str-074', category: 'strategy', text: '"Logistics" is the art of moving and supplying forces, often decisive in long campaigns.' },
  { id: 'str-075', category: 'strategy', text: 'A "war of manoeuvre" seeks decisive results through movement rather than static lines.' },
  { id: 'str-076', category: 'strategy', text: 'In chess, a "passed pawn" has no enemy pawns blocking its path to promotion.' },
  { id: 'str-077', category: 'strategy', text: '"Command and control" is the exercise of authority over forces to achieve a mission.' },
  { id: 'str-078', category: 'strategy', text: 'A "force multiplier" increases the effectiveness of a given force.' },
  { id: 'str-079', category: 'strategy', text: 'A "standoff" is a situation where neither side can gain a decisive advantage.' },
  { id: 'str-080', category: 'strategy', text: '"Pre-emption" strikes first to prevent an anticipated attack.' },
  { id: 'str-081', category: 'strategy', text: 'In chess, the "opening" is the initial phase of development and fighting for the centre.' },
  { id: 'str-082', category: 'strategy', text: 'A "war of position" relies on fortified lines rather than rapid movement.' },
  { id: 'str-083', category: 'strategy', text: '"Morale" — the will of a force — can decide battles as much as numbers do.' },
  { id: 'str-084', category: 'strategy', text: 'A "decoy" is used to mislead an opponent about one’s true intentions.' },
  { id: 'str-085', category: 'strategy', text: '"Mission command" gives subordinates freedom to act within the commander’s intent.' },
  { id: 'str-086', category: 'strategy', text: '"Overextension" leaves a force stretched too thin to defend its gains.' },
  { id: 'str-087', category: 'strategy', text: 'A "counterattack" strikes back after blunting an opponent’s assault.' },
  { id: 'str-088', category: 'strategy', text: 'Good intelligence — knowing the enemy and the ground — is a foundation of strategy.' },
  { id: 'str-089', category: 'strategy', text: 'A reserve of troops or resources is held back for the decisive moment.' },
  { id: 'str-090', category: 'strategy', text: 'In chess, a "zwischenzug" is an in-between move made before an expected reply.' },
  { id: 'str-091', category: 'strategy', text: '"Deception" aims to make an opponent believe something false about one’s plans.' },
  { id: 'str-092', category: 'strategy', text: 'Concentration of force and surprise are among the classic principles of war.' },
  { id: 'str-093', category: 'strategy', text: 'A "war of nerves" uses psychological pressure to weaken an opponent’s resolve.' },
  { id: 'str-094', category: 'strategy', text: 'In business, a "loss leader" is priced low to draw customers who then buy other goods.' },
  { id: 'str-095', category: 'strategy', text: '"Redundancy" builds in backups so a single failure does not cause collapse.' },
  { id: 'str-096', category: 'strategy', text: 'A "feedback loop" lets a strategy adjust based on the results it produces.' },
  { id: 'str-097', category: 'strategy', text: '"Iterative planning" refines a plan through repeated cycles rather than fixing it once.' },
  { id: 'str-098', category: 'strategy', text: 'A "contingency plan" prepares an alternative course for when things go wrong.' },
  { id: 'str-099', category: 'strategy', text: '"Timing" — striking when conditions are most favourable — is central to strategy.' },
  { id: 'str-100', category: 'strategy', text: 'Turning a vague goal into a concrete next step is how a plan becomes action.' },

  // ── Mythology ────────────────────────────────────────────────────────────
  { id: 'myt-001', category: 'mythology', text: 'In Greek myth, Prometheus stole fire from the gods and gave it to humankind.' },
  { id: 'myt-002', category: 'mythology', text: 'The Norse god Odin sacrificed one of his eyes for wisdom at the well of Mimir.' },
  { id: 'myt-003', category: 'mythology', text: 'In Egyptian myth, Anubis, the jackal-headed god, guided and protected the dead.' },
  { id: 'myt-004', category: 'mythology', text: 'The labyrinth of Greek myth was built by Daedalus to contain the Minotaur.' },
  { id: 'myt-005', category: 'mythology', text: 'In Norse mythology, the rainbow bridge Bifröst links the human world to Asgard.' },
  { id: 'myt-006', category: 'mythology', text: 'The phoenix, found in several mythologies, is reborn from the ashes of its predecessor.' },
  { id: 'myt-007', category: 'mythology', text: 'Icarus fell because he flew too close to the sun, melting the wax of his wings.' },
  { id: 'myt-008', category: 'mythology', text: 'Thor, the Norse thunder god, wields the hammer Mjölnir.' },
  { id: 'myt-009', category: 'mythology', text: 'In Greek myth, the Sirens lured sailors to their deaths with enchanting song.' },
  { id: 'myt-010', category: 'mythology', text: 'The Roman god Janus, of doorways and beginnings, is depicted with two faces looking both ways.' },
  { id: 'myt-011', category: 'mythology', text: 'In Greek myth, Pandora’s jar released all the world’s troubles, leaving only hope inside.' },
  { id: 'myt-012', category: 'mythology', text: 'The many-headed Hydra grew two heads for each one cut off, until Heracles defeated it.' },
  { id: 'myt-013', category: 'mythology', text: 'Yggdrasil, the world tree of Norse myth, connects the nine worlds.' },
  { id: 'myt-014', category: 'mythology', text: 'In Greek myth, Charon ferried the souls of the dead across the river Styx.' },
  { id: 'myt-015', category: 'mythology', text: 'The Sphinx of Greek myth killed those who could not answer its riddle.' },
  { id: 'myt-016', category: 'mythology', text: 'In Greek myth, Zeus was king of the gods and ruler of the sky.' },
  { id: 'myt-017', category: 'mythology', text: 'Poseidon was the Greek god of the sea and earthquakes.' },
  { id: 'myt-018', category: 'mythology', text: 'Hades ruled the underworld in Greek mythology.' },
  { id: 'myt-019', category: 'mythology', text: 'Athena, goddess of wisdom and war, was said to have sprung from the head of Zeus.' },
  { id: 'myt-020', category: 'mythology', text: 'Apollo was the Greek god of music, prophecy, and the sun.' },
  { id: 'myt-021', category: 'mythology', text: 'Artemis was the Greek goddess of the hunt and the Moon.' },
  { id: 'myt-022', category: 'mythology', text: 'Hermes served as the messenger of the Greek gods and wore winged sandals.' },
  { id: 'myt-023', category: 'mythology', text: 'Aphrodite was the Greek goddess of love and beauty.' },
  { id: 'myt-024', category: 'mythology', text: 'Ares was the Greek god of war.' },
  { id: 'myt-025', category: 'mythology', text: 'Hephaestus, the Greek god of the forge, crafted weapons and wonders for the gods.' },
  { id: 'myt-026', category: 'mythology', text: 'In Greek myth, Heracles performed twelve labours as penance.' },
  { id: 'myt-027', category: 'mythology', text: 'The Trojan War of Greek legend was sparked by the abduction of Helen.' },
  { id: 'myt-028', category: 'mythology', text: 'The Trojan Horse let Greek soldiers enter the city of Troy by deception.' },
  { id: 'myt-029', category: 'mythology', text: 'Odysseus took ten years to return home after the Trojan War, as told in the Odyssey.' },
  { id: 'myt-030', category: 'mythology', text: 'Achilles was said to be invulnerable except for his heel.' },
  { id: 'myt-031', category: 'mythology', text: 'In Norse myth, Ragnarök is a foretold battle bringing the end and renewal of the world.' },
  { id: 'myt-032', category: 'mythology', text: 'Loki is a cunning trickster figure in Norse mythology.' },
  { id: 'myt-033', category: 'mythology', text: 'Freyja was a Norse goddess linked to love, beauty, and war.' },
  { id: 'myt-034', category: 'mythology', text: 'The Valkyries chose who would fall in battle and brought them to Valhalla.' },
  { id: 'myt-035', category: 'mythology', text: 'Valhalla was the hall where slain warriors feasted in Norse myth.' },
  { id: 'myt-036', category: 'mythology', text: 'Fenrir is a monstrous wolf in Norse mythology.' },
  { id: 'myt-037', category: 'mythology', text: 'Jörmungandr, the Midgard Serpent, encircles the world in Norse myth.' },
  { id: 'myt-038', category: 'mythology', text: 'In Egyptian myth, Ra was the sun god who sailed across the sky each day.' },
  { id: 'myt-039', category: 'mythology', text: 'Osiris was the Egyptian god of the afterlife and rebirth.' },
  { id: 'myt-040', category: 'mythology', text: 'Isis was a major Egyptian goddess associated with magic and motherhood.' },
  { id: 'myt-041', category: 'mythology', text: 'Horus, often shown with a falcon’s head, was an Egyptian sky god.' },
  { id: 'myt-042', category: 'mythology', text: 'Set was the Egyptian god of chaos, storms, and the desert.' },
  { id: 'myt-043', category: 'mythology', text: 'The Egyptian Book of the Dead held spells to guide souls in the afterlife.' },
  { id: 'myt-044', category: 'mythology', text: 'In Egyptian belief, the heart was weighed against a feather to judge the dead.' },
  { id: 'myt-045', category: 'mythology', text: 'In Roman myth, Jupiter was the king of the gods, like the Greek Zeus.' },
  { id: 'myt-046', category: 'mythology', text: 'Mars was the Roman god of war.' },
  { id: 'myt-047', category: 'mythology', text: 'Venus was the Roman goddess of love, like the Greek Aphrodite.' },
  { id: 'myt-048', category: 'mythology', text: 'Neptune was the Roman god of the sea.' },
  { id: 'myt-049', category: 'mythology', text: 'In Roman legend, Romulus and Remus were raised by a she-wolf.' },
  { id: 'myt-050', category: 'mythology', text: 'Mercury was the Roman messenger god, like the Greek Hermes.' },
  { id: 'myt-051', category: 'mythology', text: 'The Titans of Greek myth were an older generation of gods overthrown by the Olympians.' },
  { id: 'myt-052', category: 'mythology', text: 'Cronus, a Titan, was overthrown by his son Zeus.' },
  { id: 'myt-053', category: 'mythology', text: 'Atlas, a Titan, was condemned to hold up the sky.' },
  { id: 'myt-054', category: 'mythology', text: 'The Muses of Greek myth inspired art, music, and learning.' },
  { id: 'myt-055', category: 'mythology', text: 'The Fates of Greek myth were three goddesses who spun the thread of each life.' },
  { id: 'myt-056', category: 'mythology', text: 'Persephone’s time in the underworld was said to explain the changing seasons.' },
  { id: 'myt-057', category: 'mythology', text: 'Orpheus tried to bring his wife back from the underworld with his music.' },
  { id: 'myt-058', category: 'mythology', text: 'Medusa was a Gorgon whose gaze turned onlookers to stone.' },
  { id: 'myt-059', category: 'mythology', text: 'Perseus slew Medusa and used her head as a weapon.' },
  { id: 'myt-060', category: 'mythology', text: 'A centaur was a creature that was half human and half horse.' },
  { id: 'myt-061', category: 'mythology', text: 'Pegasus was a winged horse of Greek mythology.' },
  { id: 'myt-062', category: 'mythology', text: 'The Minotaur, half man and half bull, lived in the Labyrinth of Crete.' },
  { id: 'myt-063', category: 'mythology', text: 'Theseus killed the Minotaur and escaped the Labyrinth with Ariadne’s thread.' },
  { id: 'myt-064', category: 'mythology', text: 'Tantalus was punished with food and water forever out of reach.' },
  { id: 'myt-065', category: 'mythology', text: 'Sisyphus was condemned to roll a boulder uphill only for it to roll back down forever.' },
  { id: 'myt-066', category: 'mythology', text: 'The cyclops of Greek myth was a giant with a single eye.' },
  { id: 'myt-067', category: 'mythology', text: 'In the Odyssey, Odysseus blinded the cyclops Polyphemus to escape.' },
  { id: 'myt-068', category: 'mythology', text: 'The Greek underworld was guarded by the many-headed dog Cerberus.' },
  { id: 'myt-069', category: 'mythology', text: 'In Hindu belief, Vishnu is a preserver god who appears in many earthly forms.' },
  { id: 'myt-070', category: 'mythology', text: 'In Hindu belief, Shiva is associated with destruction and renewal.' },
  { id: 'myt-071', category: 'mythology', text: 'In Hindu belief, Brahma is regarded as the creator.' },
  { id: 'myt-072', category: 'mythology', text: 'The elephant-headed god Ganesha is honoured in Hinduism as a remover of obstacles.' },
  { id: 'myt-073', category: 'mythology', text: 'In Japanese mythology, Amaterasu is the sun goddess.' },
  { id: 'myt-074', category: 'mythology', text: 'In Chinese mythology, dragons are linked to water, rain, and good fortune.' },
  { id: 'myt-075', category: 'mythology', text: 'The phoenix appears in Chinese mythology as a symbol of virtue and grace.' },
  { id: 'myt-076', category: 'mythology', text: 'In Greek myth, ambrosia and nectar were the food and drink of the gods.' },
  { id: 'myt-077', category: 'mythology', text: 'Mount Olympus was believed to be the home of the Greek gods.' },
  { id: 'myt-078', category: 'mythology', text: 'Odin’s ravens, Huginn and Muninn, brought him news from across the world.' },
  { id: 'myt-079', category: 'mythology', text: 'Odin’s eight-legged horse Sleipnir could travel between worlds.' },
  { id: 'myt-080', category: 'mythology', text: 'In Norse myth, the beloved god Baldr’s death was a great tragedy.' },
  { id: 'myt-081', category: 'mythology', text: 'The Norns of Norse myth shaped the destiny of gods and humans.' },
  { id: 'myt-082', category: 'mythology', text: 'Dionysus was the Greek god of wine and revelry.' },
  { id: 'myt-083', category: 'mythology', text: 'Hera was the Greek queen of the gods and wife of Zeus.' },
  { id: 'myt-084', category: 'mythology', text: 'Demeter was the Greek goddess of the harvest and agriculture.' },
  { id: 'myt-085', category: 'mythology', text: 'Hestia was the Greek goddess of the hearth and home.' },
  { id: 'myt-086', category: 'mythology', text: 'In Egyptian myth, Thoth was the god of writing and wisdom.' },
  { id: 'myt-087', category: 'mythology', text: 'In Egyptian myth, Bastet was a goddess often depicted as a cat.' },
  { id: 'myt-088', category: 'mythology', text: 'The Great Sphinx of Egyptian art has a human head and a lion’s body.' },
  { id: 'myt-089', category: 'mythology', text: 'In Greek myth, Prometheus was punished for giving fire to humanity.' },
  { id: 'myt-090', category: 'mythology', text: 'Pan was the Greek god of the wild, shepherds, and flocks.' },
  { id: 'myt-091', category: 'mythology', text: 'The griffin was a mythical beast with a lion’s body and an eagle’s head and wings.' },
  { id: 'myt-092', category: 'mythology', text: 'The Mesopotamian Epic of Gilgamesh tells of a king’s search for immortality.' },
  { id: 'myt-093', category: 'mythology', text: 'In Norse myth, Tyr was a god associated with law and heroic glory.' },
  { id: 'myt-094', category: 'mythology', text: 'The Norse god Heimdall guarded the rainbow bridge to Asgard.' },
  { id: 'myt-095', category: 'mythology', text: 'Charon required payment to ferry souls across the river Styx.' },
  { id: 'myt-096', category: 'mythology', text: 'In Aztec mythology, Quetzalcoatl was a feathered-serpent deity.' },
  { id: 'myt-097', category: 'mythology', text: 'Nike was the Greek goddess of victory.' },
  { id: 'myt-098', category: 'mythology', text: 'Eros was a Greek god of love and desire.' },
  { id: 'myt-099', category: 'mythology', text: 'In Norse myth, the realm of the dead ruled by the goddess Hel shares her name.' },
  { id: 'myt-100', category: 'mythology', text: 'The unicorn, a horse-like creature with a single horn, appears in many legends.' },
]
